=== matt-dunn/rpi-utilitiescontentbuild/Src/RPI/Utilities/ContentBuild/Lib/Configuration/Xml/Model/Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
	targetNamespace="http://www.rpi.co.uk/"
    xmlns:commonType="http://www.rpi.co.uk/presentation/config/type"
	xmlns:RPI="http://www.rpi.co.uk/">

	<xs:import namespace="http://www.rpi.co.uk/presentation/config/type" schemaLocation="../../../../../../../../vendor/rpi/schemas/Src/RPI/Schemas/Conf/Common/Types.xsd"/>
    
	<xs:simpleType name="contentType">
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="js"/>
			<xs:enumeration value="css"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="project">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" ref="RPI:processors"/>
				<xs:element minOccurs="0" maxOccurs="1" ref="RPI:uriResolvers"/>
				<xs:element minOccurs="0" maxOccurs="1" ref="RPI:plugins"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="RPI:build"/>
			</xs:sequence>
			<xs:attribute name="appRoot" use="required" type="xs:normalizedString"/>
			<xs:attribute name="name" use="required" type="xs:normalizedString"/>
			<xs:attribute name="prefix" use="required" type="xs:normalizedString"/>
			<xs:attribute name="basePath" use="optional" type="xs:normalizedString"/>
		</xs:complexType>
	</xs:element>

    <xs:element name="processors">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="RPI:processor"/>
			</xs:sequence>
        </xs:complexType>    
    </xs:element>

    <xs:element name="processor">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="RPI:param"/>
			</xs:sequence>
			<xs:attribute name="type" use="required" type="commonType:namespacedObjectName"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="uriResolvers">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="RPI:uriResolver"/>
			</xs:sequence>
        </xs:complexType>    
    </xs:element>

    <xs:element name="uriResolver">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="RPI:param"/>
			</xs:sequence>
			<xs:attribute name="type" use="required" type="commonType:namespacedObjectName"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="plugins">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="RPI:plugin"/>
			</xs:sequence>
        </xs:complexType>    
    </xs:element>

    <xs:element name="plugin">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="RPI:param"/>
			</xs:sequence>
			<xs:attribute name="interface" use="required" type="commonType:namespacedObjectName"/>
			<xs:attribute name="type" use="required" type="commonType:namespacedObjectName"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="param">
		<xs:complexType mixed="true">
			<xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" namespace="##targetNamespace"/>
			</xs:sequence>
        </xs:complexType>    
    </xs:element>
    
	<xs:element name="build">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="RPI:files"/>
			</xs:sequence>
			<xs:attribute name="buildDirectory" use="required" type="xs:normalizedString"/>
			<xs:attribute name="name" use="required" type="xs:normalizedString"/>
			<xs:attribute name="outputDirectory" use="optional" type="xs:normalizedString"/>
			<xs:attribute name="type" use="required" type="RPI:contentType"/>
            
			<xs:attribute name="media" use="optional" type="xs:normalizedString"/>
			<xs:attribute name="target" use="optional" type="xs:normalizedString"/>

			<xs:attribute name="outputFilename" use="optional" type="xs:normalizedString"/>

			<xs:attribute name="externalDependenciesNames" use="optional" type="xs:normalizedString">
				<xs:annotation>
					<xs:documentation>
						Comma separated list of build names that specify dependencies outside this build file
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="files">
		<xs:complexType>
			<xs:attribute name="name" use="optional" type="xs:normalizedString"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== matt-dunn/rpi-utilitiescontentbuild/Test/Src/RPI/Utilities/ContentBuild/Test/Lib/Configuration/Xml/ProjectTest/ui.build-multiple-plugins.xml
<?xml version="1.0" encoding="UTF-8"?>
<project
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.rpi.co.uk/ ../../../../../../../../../../Src/RPI/Utilities/ContentBuild/Lib/Configuration/Xml/Model/Schema.xsd"

    xmlns="http://www.rpi.co.uk/" name="website" prefix="TEMPLATE" appRoot="ROOT" basePath="">
    
    <processors>
        <processor type="RPI\Utilities\ContentBuild\Processors\Images"/>
        <processor type="RPI\Utilities\ContentBuild\Processors\HashImages">
            <param>
                <hashAlgorithm>md5</hashAlgorithm>
            </param>
        </processor>
    </processors>
    
    <uriResolvers>
        <uriResolver type="RPI\Utilities\ContentBuild\UriResolvers\Composer">
            <param>
                <vendorPath>../../../../../../../../../../vendor</vendorPath>
            </param>
        </uriResolver>
    </uriResolvers>
    
    <plugins>
        <plugin interface="RPI\Utilities\ContentBuild\Lib\Model\Plugin\ICompressor" type="RPI\Utilities\ContentBuild\Plugins\YuglifyCompressor">
            <param>
                <testParam>value for test param</testParam>
            </param>
        </plugin>
    </plugins>
    
    <build buildDirectory="" outputDirectory="compiled/css/" type="css" name="core" media="all" outputFilename="test.css">
        <files name="test.css"/>
    </build>
    
    <build buildDirectory="" outputDirectory="compiled/js/" type="js" name="core" media="all" externalDependenciesNames="core" target="footer">
        <files name="test.js"/>
    </build>
</project>
